<h2>Catégories</h2>
<ul class="list-unstyled d-flex">
<?php foreach($productLines as $product) : ?>
    <li>
        
        <a href="productLine.php?id=<?=$product['productLine']?>" class="btn btn-primary mx-1">
            <?=$product['productLine']?><br>
            <span class="badge text-bg-danger"><?=$product['quantity']?></span>
        </a>
       
    </li>
    <?php endforeach; ?>
</ul>


