<h2>Top <?=count($bestCustomers)?> des clients</h2>
<table class="table table-sm table-striped table-hover">
   
    <tr>
        <th class="px-3">CLIENT</th>
        <th class="px-3">Chiffre d'affaire</th>
    </tr>
    <?php foreach($bestCustomers as $bestCustomer) : ?>
    <tr>
        <td class="px-3">
            <a href="customer.php?id=<?=$bestCustomer['customerNumber']?>">
            <?=$bestCustomer['customerName']?>
            </a>
        </td>
        <td class="px-3"><?=euro($bestCustomer['CA'])?></td>
    </tr>
    <?php endforeach; ?>
</table>