<h2>Top <?=COUNT($bestSellersProduct) ?> des produits</h2>
<table class="table table-sm table-striped table-hover">



    <tr>
        <th class="px-3">Produit</th>
        <th class="px-3">Pièces vendues</th>
    </tr>
    <?php foreach($bestSellersProduct as $bestSellers) : ?>
    <tr>
        <td class="px-3">
            <a href="product.php?id=<?=$bestSellers['productCode']?>">
                <?=$bestSellers['productName']?>
                
            </a>
        </td>
        <td class="px-3"><?=$bestSellers['quantity']?></td>
    </tr>
    <?php endforeach;?>
</table>