<?php include './templates/blocs/header.phtml' ?>
    <header>


    


        <div class="container">
        <h1>Commande n° <?=$orderByNumbers['orderNumber']?></h1>
            <div class="row">
                <div class="col-6">
                  
                    
                <strong>Date de commande&nbsp;: </strong><?= $orderByNumbers['orderDate'] ?><br>
                    <?php
                    $status = "success";
                    if ($orderByNumbers['status'] == 'Cancelled') {
                        $status = 'danger';
                    } elseif ($orderByNumbers['status'] == 'Disputed') {
                        $status = 'warning';
                    } elseif ($orderByNumbers['status'] == 'In Process') {
                        $status = 'primary';
                    }
                    ?>
                    <strong>Statut&nbsp;: </strong><span class="badge text-bg-<?= $status ?>"><?= $orderByNumbers['status'] ?></span><br>
                    <strong>Commentaires&nbsp;: </strong><br>
                   <p>
                    <?=$orderByNumbers['comments']?>
                   </p>
                </div>
                <div class="col-6">
                    <h2><a href="customer.php?id=<?=$orderByNumbers['customerNumber']?>"><?=$orderByNumbers['customerName']?></a></h2>
                    <h3><?=$orderByNumbers['contactLastName']?> <?=$orderByNumbers['contactFirstName']?></h3>
                    <strong><?=$orderByNumbers['phone']?></strong><br>
                    <strong><?=$orderByNumbers['addressLine1']?></strong><br>

                    <?php if($orderByNumbers['addressLine2'] != ""):?>
                    <strong><?=$orderByNumbers['addressLine2']?></strong><br>
                    <?php endif;?>
                    <strong>
                    <?=$orderByNumbers['postalCode']?> -
                    <?=$orderByNumbers['city']?> -
                    <?php if($orderByNumbers['state'] != ""):?> 
                    <?=$orderByNumbers['state']?> -
                    <?php endif;?>
                    <?=$orderByNumbers['country']?>
                    </strong>
                </div>
            </div>
        </div>


    </header>
    <main>
        <section id="order-detail">
            <div class="container">
                <div class="row">
                    <div class="col">
                        <h2>Détail de la commande</h2>
                        <table class="table table-sm table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>Code produit</th>
                                    <th>Dénomination</th>
                                    <th>Catégorie</th>
                                    <th>Échelle</th>
                                    <th>Quantité</th>
                                    <th>Prix unitaire</th>
                                    <th>Total</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach($orderDetails as $orderDetail) : ?>
                                <tr>
                                    <td><a href="product.php?id=<?=$orderDetail['productCode']?>"><?=$orderDetail['productCode']?></a></td>
                                    <td><a href="product.php?id=<?=$orderDetail['productCode']?>"><?=$orderDetail['productName']?></a></td>
                                    <td><a href="productline.php?id=<?=$orderDetail['productCode']?>"><?=$orderDetail['productLine']?></a></td>
                                    <td><?=$orderDetail['productScale']?></td>
                                    <td><?=$orderDetail['quantityOrdered']?></td>
                                    <td><?=$orderDetail['priceEach']?></td>
                                    <td><?=$orderDetail['total']?></td>
                                </tr>
                                <?php endforeach; ?>
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="6"></td>
                                    <td><h5><?=euro($orderByNumbers['TOTAL'])?></h5></td>
                                </tr>
                             
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </main>
<?php include './templates/blocs/footer.phtml' ?>